name: CI 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME} 
  MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
  MONGODB_URI: "mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@mongo:27017"

jobs:

  build-and-test:
    name: Run unit tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    services:

      mongo:
        image: mongo 
        env:
          MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME} 
          MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
          MONGODB_URI: "mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@mongo:27017"
        volumes:
          - db:/data/db 
        ports:
          - 27017:27017 
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 16.X

    - name: Install dependencies
      run: yarn install
    - run: yarn test
    - run: yarn build
    - run: yarn test:e2e 


    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{secrets.DOCKER_AUTH_USERNAME}} 
        password: ${{secrets.DOCKER_AUTH_TOKEN}}

    - name: Build and push Docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: ./api
        push: true
        tags: ${{secrets.DOCKER_AUTH_USERNAME}}/monapi:${{github.sha}} 
        file: ./api/Dockerfile
        
    - run: node.client.js
  



